### PR TITLE
Add parler-related migration in example app

### PR DESCRIPTION
**Pull request by yakky**
django-parler 2.0 require a migration

we need to add this migration the example app to allow tests to pass

### CODE REVIEW

**Comment by yakky** [comment]
@FinalAngel could you give a look at this?

**Comment by FinalAngel** [comment]
@yakky looks fairly straight forward 👍

**Comment by yakky** [comment]
@FinalAngel could you merge this yourself? I don't have permissions anymore since moving this to `divio` org

**Comment by FinalAngel** [comment]
@yakky let's fix that! Can you now?

**Comment by yakky** [comment]
@FinalAngel yes, thanks, merging this

**Pull request merged**
